import { useState } from 'react'
import {
  PRIMAL_ELEMENTS, CATALYST_ELEMENTS, ELEMENT_COMBINATIONS,
  MANA_POLARITIES, SUPREME_ELEMENTS,
  CORE_STATES, ALL_PILLARS, PILLAR_TIERS, SPELL_LEVELS,
} from '../data/elements'

const TIER_ORDER = ['fundamental', 'refined', 'sovereign']

export default function MagicSystem() {
  const [activeSection, setActiveSection] = useState('equation')
  const [hoveredCombo, setHoveredCombo] = useState(null)
  const [selectedCombo, setSelectedCombo] = useState(null)
  const [selectedPillar, setSelectedPillar] = useState(null)
  const [selectedState, setSelectedState] = useState(null)

  const sections = [
    { id: 'equation',  label: 'The Equation',     icon: '◑' },
    { id: 'pillars',   label: '15 Pillars',        icon: '⊞' },
    { id: 'matrix',    label: 'Combo Matrix',      icon: '⊛' },
    { id: 'states',    label: 'Core States',       icon: '◈' },
    { id: 'levels',    label: 'Spell Levels',      icon: '⊟' },
  ]

  const displayCombo = hoveredCombo || selectedCombo

  return (
    <div className="magic-system-view">
      {/* Top tabs */}
      <div className="magic-tabs">
        {sections.map(s => (
          <button
            key={s.id}
            className={`magic-tab ${activeSection === s.id ? 'active' : ''}`}
            onClick={() => setActiveSection(s.id)}
          >
            <span className="magic-tab-icon">{s.icon}</span>
            <span>{s.label}</span>
          </button>
        ))}
      </div>

      <div className="magic-content">

        {/* ── THE EQUATION ─────────────────────────────────────────────── */}
        {activeSection === 'equation' && (
          <div className="eq-view">
            <div className="eq-hero">
              <div className="eq-row">
                <div className="eq-term aura-term">
                  <div className="eq-glyph" style={{ color: '#FF6644' }}>◑</div>
                  <div className="eq-name">Aura</div>
                  <div className="eq-desc">Physical energy generated by the body. The basis of beast manifestation and raw physical force.</div>
                  <div className="eq-sub">Dominant in Alma (60/40)</div>
                </div>
                <div className="eq-op">+</div>
                <div className="eq-term force-term">
                  <div className="eq-glyph" style={{ color: '#44AAFF' }}>◐</div>
                  <div className="eq-name">Force</div>
                  <div className="eq-desc">Mental energy generated by the mind. The basis of tool creation and will projection.</div>
                  <div className="eq-sub">Dominant in Spirits (60/40)</div>
                </div>
                <div className="eq-op">=</div>
                <div className="eq-term mana-term">
                  <div className="eq-glyph" style={{ color: '#D4AF37' }}>◈</div>
                  <div className="eq-name">Mana</div>
                  <div className="eq-desc">The native energy of all coreporial beings. Accesses the 15 Pillars through the Core. Named after Mana the Conceptual.</div>
                  <div className="eq-sub">Balanced in Ascen (50/50)</div>
                </div>
              </div>

              <div className="eq-note-block">
                <div className="eq-note-title">The Source</div>
                <p>Mana (the person) was the first being simultaneously blessed by both the Harmony and Chaos Pillars — the structural opposites that define the character of all mana energy. His existence was magic itself. When he taught the Ascen, the language he spoke became the foundation of structured spell-casting. The substance was named in his honor after his death. Every spell cast in the known world runs on a framework he left behind.</p>
              </div>

              <div className="eq-note-block">
                <div className="eq-note-title">The Balance System</div>
                <div className="eq-balance-grid">
                  <div className="eq-balance-card" style={{ borderColor: '#FF664444' }}>
                    <div style={{ color: '#FF6644', fontWeight: 700, marginBottom: 6 }}>Aura-Dominant (Alma)</div>
                    <div>60% Aura / 40% Force. Body adapts to channel the Ferali's Mana-Aura nature. Beast characteristics merge internally — traits, elements, abilities manifest through the body directly. The 40% Force becomes the dedicated supply the beast draws on during manifestation.</div>
                  </div>
                  <div className="eq-balance-card" style={{ borderColor: '#44AAFF44' }}>
                    <div style={{ color: '#44AAFF', fontWeight: 700, marginBottom: 6 }}>Force-Dominant (Spirits)</div>
                    <div>60% Force / 40% Aura. Body adapts to channel the Celestials' Mana-Force nature. Tool power flows through the body rather than from an external weapon. The 40% Aura becomes the dedicated supply the tool draws on to manifest and maintain its presence.</div>
                  </div>
                  <div className="eq-balance-card" style={{ borderColor: '#D4AF3744' }}>
                    <div style={{ color: '#D4AF37', fontWeight: 700, marginBottom: 6 }}>Balanced (Ascen)</div>
                    <div>50% Aura / 50% Force. The original Orian constitution — those who refused all contracts. No dominant component. Full lifespan (200–300 years via training, max 2 children). No internal beast or tool merge. Maximum magical breadth.</div>
                  </div>
                </div>
              </div>

              <div className="eq-note-block">
                <div className="eq-note-title">Mana Polarities</div>
                <div className="eq-polarity-row">
                  {MANA_POLARITIES.map(p => (
                    <div key={p.id} className="eq-polarity-card" style={{ borderColor: `${p.color}44` }}>
                      <div className="eq-polarity-glyph" style={{ color: p.color }}>{p.glyph}</div>
                      <div className="eq-polarity-name" style={{ color: p.color }}>{p.name}</div>
                      <div className="eq-polarity-desc">{p.description}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ── 15 PILLARS ───────────────────────────────────────────────── */}
        {activeSection === 'pillars' && (
          <div className="pillars-view">
            <div className="pillars-header">
              <div className="pillars-title-row">
                <h2 className="pillars-h2">The 15 Pillars</h2>
                <span className="pillars-subtitle">The structural axes of all mana in existence</span>
              </div>
            </div>

            {PILLAR_TIERS.map(tier => (
              <div key={tier.id} className="pillar-tier-block">
                <div className="pillar-tier-header" style={{ borderColor: `${tier.color}66` }}>
                  <span className="pillar-tier-name" style={{ color: tier.color }}>{tier.label}</span>
                  <span className="pillar-tier-pct">{tier.pct}</span>
                  <span className="pillar-tier-desc">{tier.desc}</span>
                </div>
                <div className="pillar-card-grid">
                  {ALL_PILLARS.filter(p => p.tier === tier.id).map(pillar => (
                    <button
                      key={pillar.id}
                      className={`pillar-card ${selectedPillar?.id === pillar.id ? 'selected' : ''}`}
                      style={{ '--pillar-color': pillar.color, borderColor: selectedPillar?.id === pillar.id ? pillar.color : 'var(--border)' }}
                      onClick={() => setSelectedPillar(selectedPillar?.id === pillar.id ? null : pillar)}
                    >
                      <div className="pillar-card-glyph" style={{ color: pillar.color }}>{pillar.glyph}</div>
                      <div className="pillar-card-name">{pillar.name}</div>
                      <div className="pillar-card-pct" style={{ color: pillar.color }}>{pillar.pct}</div>
                    </button>
                  ))}
                </div>
                {selectedPillar && ALL_PILLARS.find(p => p.id === selectedPillar.id)?.tier === tier.id && (
                  <div className="pillar-detail" style={{ borderColor: `${selectedPillar.color}55` }}>
                    <div className="pillar-detail-name" style={{ color: selectedPillar.color }}>
                      {selectedPillar.glyph} {selectedPillar.name}
                    </div>
                    <div className="pillar-detail-tier" style={{ color: selectedPillar.color }}>
                      {selectedPillar.tierLabel} · {selectedPillar.pct}
                    </div>
                    <div className="pillar-detail-desc">{selectedPillar.desc}</div>
                  </div>
                )}
              </div>
            ))}

            <div className="pillar-tier-block">
              <div className="pillar-tier-header" style={{ borderColor: '#5F4BB666' }}>
                <span className="pillar-tier-name" style={{ color: '#5F4BB6' }}>Conceptual-Level</span>
                <span className="pillar-tier-pct">Irane only</span>
                <span className="pillar-tier-desc">Elements that operate outside the normal Pillar framework. Cannot be channelled through technique — only through a Conceptual nature. Mana's domain was Magic itself; Irane's domain is Irane Material / all Cores.</span>
              </div>
              <div className="pillar-card-grid">
                {SUPREME_ELEMENTS.map(el => (
                  <button key={el.id} className="pillar-card" style={{ '--pillar-color': el.color, borderColor: 'var(--border)' }}
                    onClick={() => setSelectedPillar(selectedPillar?.id === el.id ? null : el)}>
                    <div className="pillar-card-glyph" style={{ color: el.color }}>{el.glyph}</div>
                    <div className="pillar-card-name">{el.name}</div>
                    <div className="pillar-card-pct" style={{ color: el.color }}>Conceptual</div>
                  </button>
                ))}
              </div>
              {selectedPillar && SUPREME_ELEMENTS.find(e => e.id === selectedPillar.id) && (
                <div className="pillar-detail" style={{ borderColor: `${selectedPillar.color}55` }}>
                  <div className="pillar-detail-name" style={{ color: selectedPillar.color }}>
                    {selectedPillar.glyph} {selectedPillar.name}
                  </div>
                  <div className="pillar-detail-tier" style={{ color: selectedPillar.color }}>Conceptual-Level</div>
                  <div className="pillar-detail-desc">{selectedPillar.description || selectedPillar.desc}</div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* ── COMBINATION MATRIX ───────────────────────────────────────── */}
        {activeSection === 'matrix' && (
          <div className="matrix-view">
            <div className="matrix-header">
              <h2 className="matrix-h2">Element Combination Matrix</h2>
              <p className="matrix-sub">Each Refined element combines with every Fundamental element to produce a unique Advanced Form. Hover or click any cell to inspect.</p>
            </div>

            <div className="matrix-grid-wrap">
              {/* Column headers — Fundamental elements */}
              <div className="matrix-grid" style={{ gridTemplateColumns: `120px repeat(${PRIMAL_ELEMENTS.length}, 1fr)` }}>
                <div className="matrix-corner" />
                {PRIMAL_ELEMENTS.map(el => (
                  <div key={el.id} className="matrix-col-hdr" style={{ borderBottom: `2px solid ${el.color}66` }}>
                    <span className="matrix-el-glyph" style={{ color: el.color }}>{el.glyph}</span>
                    <span className="matrix-el-name" style={{ color: el.color }}>{el.name}</span>
                  </div>
                ))}

                {/* Rows — Catalyst elements */}
                {CATALYST_ELEMENTS.map(cat => (
                  [
                    <div key={`${cat.id}-lbl`} className="matrix-row-hdr" style={{ borderRight: `2px solid ${cat.color}66` }}>
                      <span className="matrix-el-glyph" style={{ color: cat.color }}>{cat.glyph}</span>
                      <span className="matrix-el-name" style={{ color: cat.color }}>{cat.name}</span>
                    </div>,
                    ...PRIMAL_ELEMENTS.map(primal => {
                      const combo = ELEMENT_COMBINATIONS.find(c => c.catalyst === cat.id && c.primal === primal.id)
                      const isHovered = hoveredCombo?.id === combo?.id
                      const isSelected = selectedCombo?.id === combo?.id
                      return (
                        <button
                          key={`${cat.id}-${primal.id}`}
                          className={`matrix-cell ${isHovered || isSelected ? 'highlight' : ''}`}
                          style={{
                            '--combo-color': combo?.color || '#253850',
                            background: isSelected ? `${combo?.color}22` : isHovered ? `${combo?.color}14` : 'var(--card)',
                            borderColor: isSelected ? combo?.color : isHovered ? `${combo?.color}88` : 'var(--border)',
                          }}
                          onMouseEnter={() => combo && setHoveredCombo(combo)}
                          onMouseLeave={() => setHoveredCombo(null)}
                          onClick={() => combo && setSelectedCombo(selectedCombo?.id === combo.id ? null : combo)}
                        >
                          {combo ? (
                            <>
                              <div className="matrix-cell-name" style={{ color: combo.color }}>{combo.name}</div>
                              <div className="matrix-cell-affinity">{combo.affinity}</div>
                            </>
                          ) : '—'}
                        </button>
                      )
                    })
                  ]
                ))}
              </div>
            </div>

            {/* Detail panel */}
            {displayCombo && (
              <div className="combo-detail-panel" style={{ borderColor: `${displayCombo.color}55`, background: `${displayCombo.color}08` }}>
                <div className="combo-detail-name" style={{ color: displayCombo.color }}>{displayCombo.name}</div>
                <div className="combo-detail-meta">
                  <span className="combo-detail-tag" style={{ color: displayCombo.color }}>{displayCombo.affinity}</span>
                  {displayCombo.beastArchetype && (
                    <span className="combo-detail-beast">Beast Archetype: {displayCombo.beastArchetype}</span>
                  )}
                </div>
                <div className="combo-detail-desc">{displayCombo.description}</div>
                <div className="combo-detail-source">
                  <span style={{ color: 'var(--text-dim)' }}>
                    {CATALYST_ELEMENTS.find(c => c.id === displayCombo.catalyst)?.name} + {PRIMAL_ELEMENTS.find(p => p.id === displayCombo.primal)?.name}
                  </span>
                </div>
              </div>
            )}

            {!displayCombo && (
              <div className="matrix-placeholder">Hover or click a cell to see the advanced form details</div>
            )}
          </div>
        )}

        {/* ── CORE STATES ──────────────────────────────────────────────── */}
        {activeSection === 'states' && (
          <div className="states-view">
            <div className="states-header">
              <h2 className="states-h2">The 4 Core States</h2>
              <p className="states-sub">A Core State is determined by the combination of a being's <strong>Mana Polarity</strong> (Light or Darkness) and their <strong>Alignment</strong> (Harmony or Chaos). These are not choices — they are the natural expression of how a person's mana flows. Two beings with identical elements can fight completely differently based on their Core State.</p>
            </div>

            <div className="states-grid-intro">
              <div className="states-axis-row">
                <div className="states-axis-label" />
                <div className="states-axis-hdr" style={{ color: '#E8D44D' }}>☀ Light Polarity</div>
                <div className="states-axis-hdr" style={{ color: '#9B30FF' }}>◆ Dark Polarity</div>
              </div>
              <div className="states-axis-row">
                <div className="states-axis-label">∿ Harmony</div>
                <div className="states-axis-cell" style={{ color: '#E8D44D' }}>Harmonic Light</div>
                <div className="states-axis-cell" style={{ color: '#7744AA' }}>Harmonic Dark</div>
              </div>
              <div className="states-axis-row">
                <div className="states-axis-label">≋ Chaos</div>
                <div className="states-axis-cell" style={{ color: '#FF9944' }}>Chaotic Light</div>
                <div className="states-axis-cell" style={{ color: '#CC2244' }}>Chaotic Dark</div>
              </div>
            </div>

            <div className="states-cards">
              {CORE_STATES.map(state => (
                <button
                  key={state.id}
                  className={`state-card ${selectedState?.id === state.id ? 'selected' : ''}`}
                  style={{ borderColor: selectedState?.id === state.id ? state.color : 'var(--border)' }}
                  onClick={() => setSelectedState(selectedState?.id === state.id ? null : state)}
                >
                  <div className="state-card-glyphs" style={{ color: state.color }}>{state.glyphs}</div>
                  <div className="state-card-name" style={{ color: state.color }}>{state.name}</div>
                  <div className="state-card-pills">
                    <span className="state-pill" style={{ color: state.polarity === 'light' ? '#E8D44D' : '#9B30FF' }}>
                      {state.polarity === 'light' ? '☀ Light' : '◆ Dark'}
                    </span>
                    <span className="state-pill" style={{ color: state.alignment === 'harmony' ? '#4A9E7A' : '#CC5528' }}>
                      {state.alignment === 'harmony' ? '∿ Harmony' : '≋ Chaos'}
                    </span>
                  </div>
                  <div className="state-card-preview">{state.description.slice(0, 100)}…</div>
                </button>
              ))}
            </div>

            {selectedState && (
              <div className="state-detail" style={{ borderColor: `${selectedState.color}55`, background: `${selectedState.color}08` }}>
                <div className="state-detail-name" style={{ color: selectedState.color }}>
                  {selectedState.glyphs} {selectedState.name}
                </div>
                <div className="state-detail-desc">{selectedState.description}</div>
                {selectedState.coreCharacters.length > 0 && (
                  <div className="state-detail-chars">
                    Known users: <span style={{ color: selectedState.color }}>{selectedState.coreCharacters.join(', ')}</span>
                  </div>
                )}
              </div>
            )}

            <div className="states-note">
              <div className="states-note-title">The Chaos/Harmony Pillar</div>
              <p>Unlike the 15 main Pillars, Chaos and Harmony are structural axes that exist beneath all of reality — not elements a being draws from, but properties that shape how mana flows through them. Only Conceptuals are simultaneously touched by both. Mana (the person) was the only being ever blessed by both at once — making him the most structurally dangerous being in existence, a fact he did not understand until it was too late for the Primordials.</p>
            </div>
          </div>
        )}

        {/* ── SPELL LEVELS ─────────────────────────────────────────────── */}
        {activeSection === 'levels' && (
          <div className="levels-view">
            <div className="levels-header">
              <h2 className="levels-h2">Spell Level Framework</h2>
              <p className="levels-sub">Spell level is determined by the minimum mana needed to cast it at that level in the caster's primary element. A caster can use any spell at or below their level freely; they can attempt one level above with significant effort. Knowledge of a spell does not equal ability to cast it — mana strength sets the ceiling.</p>
            </div>

            <div className="levels-rules">
              <div className="levels-rule-card">
                <div className="levels-rule-title">Primary vs Secondary</div>
                <div>Casting in your primary element costs half the mana of an equivalent secondary element spell. A Level 5 Fire caster trying a Level 5 Water spell pays the full cost — and may not have the reserves for it.</div>
              </div>
              <div className="levels-rule-card">
                <div className="levels-rule-title">Reaching Beyond</div>
                <div>A caster can attempt one level above their rank using their primary element, but at significant effort — the spell costs double and taxes the body. Attempting two levels above is theoretically possible and practically suicidal.</div>
              </div>
              <div className="levels-rule-card">
                <div className="levels-rule-title">Arts vs Spells</div>
                <div>Arts are inherited abilities tied to Core nature and state — only beings of the same Core nature can teach each other Arts. Spells are external techniques anyone can learn. Arts cannot be sealed; they are what the caster is. Spells can be blocked, disrupted, and absorbed.</div>
              </div>
            </div>

            <div className="levels-list">
              {SPELL_LEVELS.map(lvl => (
                <div key={lvl.level} className="level-row" style={{ '--lvl-color': lvl.color }}>
                  <div className="level-num" style={{ color: lvl.color, borderColor: `${lvl.color}55` }}>
                    {lvl.level}
                  </div>
                  <div className="level-body">
                    <div className="level-label" style={{ color: lvl.color }}>{lvl.label}</div>
                    <div className="level-desc">{lvl.desc}</div>
                  </div>
                  <div className="level-bar-wrap">
                    <div className="level-bar" style={{ width: `${(lvl.level + 1) * 9}%`, background: lvl.color }} />
                  </div>
                </div>
              ))}
            </div>

            <div className="levels-note-block">
              <div className="levels-note-title">Arai Nexal — The Exception</div>
              <p>Arai's <em>Hands of Time</em> operates at Level 10 in Time — the theoretical ceiling for non-Conceptual beings. Time magic in Sol-Nexus does not work through parallel timelines. It works through perception: slowing, freezing, and accelerating the subjective experience of causality within her domain. At Level 10, the difference between "her perceiving time differently" and "time actually moving differently for everything in range" is not clearly distinguishable. This is why Arai's safeguard architecture for Irane is also her most ethically complex work: the person most capable of understanding what Irane is is also the person most responsible for ensuring he never finds out.</p>
            </div>
          </div>
        )}

      </div>
    </div>
  )
}
